### ISSUE TITLE
Pyside UI checklist

### ISSUE THREAD

**Issue by zpelgrims** [zpelgrims/polynomialoptics#218]
- [x] Should only stay on top of Maya session

- [x] Provide convenient way to launch it

- [x] Only one window can be created

- [x]  generate images for all the lenses

- [x]  Change image/json path to release type of way? Relative paths?
- [x]  Include images in release
- [x]  Include public database in release
