### ISSUE TITLE
1.0 Final checklist

### ISSUE THREAD

**Issue by zpelgrims** [zpelgrims/polynomialoptics#220]
- [x] Generate the best possible images for the index page
- [x] Do some last tests with production scenes

- [x] Add to site: skydome, transmitted objects won't be redistributed
- [x] Remove requirements of Z, transmitted and P aovs
- [x] re-generate c4d files, seems like the enums are hardcoded >.>

- [x] bundle with all interface files
- [x] make sure there's no absolute paths any more
- [x] add public json and svg's
- [x] is there info for all lenses?
- [x] good svg's for all lenses?

- [x] osx 5.2.0.0 release
- [x] osx 6.0.0.0 release
- [x] windows 5.2.0.0 release
- [x] windows 6.0.0.0 release
- [x] linux 5.2.0.0 release
- [x] linux 6.0.0.0 release

- [x] Gumroad production setup
- [x] Put website online
